version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
