# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections settings
# 6. Jekyll defaults settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation


# 3. Gem settings
paginate: 4 # jekyll-paginate > items per page
paginate_path: abenteuer/seite:num # jekyll-paginate > blog page
# jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
# twitter:
#  username: DavidDarnes # jekyll-seo-tag > Owners twitter username
author: Stamm Bären # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Stamm Bären Planegg # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.facebook.com/Stamm.Baeren
markdown: kramdown # Markdown parse settings
kramdown:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tasklist", "tagfilter"]

# 4. Jekyll settings
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Berlin # Timezone for blog posts and alike

# 5. Collections settings
collections:
  posts:
    title: Abenteuer # Needed for Siteleaf
    output: true
    description: "Eine Auswahl vergangener Abenteuer" # The post list page content
    feature_text:
    feature_image: "assets/images/pfadi-walk-2.jpeg"
    sort_by: date

# 6. Jekyll Default settings (see https://jekyllrb.com/docs/configuration/front-matter-defaults/)
defaults:

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: de-GE # Set the site language
title: "Stamm Bären Planegg" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo@192px.png" # Site logo, also used in jekyll-seo-tag
description: "Wir sind als örtliche Gruppe in Planegg (Bayern) Mitglied des [BdP e.V.](https://www.pfadfinden.de) und Teil der weltweiten Jugendbewegung Pfadfinden." # Site description and default description, also used in jekyll-seo-tag
url: "https://www.stamm-baeren.com" # Site url, also used in jekyll-seo-tag
baseurl: "/website-stamm-baeren"
repo: "https://github.com/ferdinand-swoboda/website-stamm-baeren"
email: "stara@stamm-baeren.com"
service_worker: false # Will turn off the service worker if set to false
css_inline: false # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/website-stamm-baeren/assets/logos/logo@16px.png'
  32: '/website-stamm-baeren/assets/logos/logo@32px.png'
  48: '/website-stamm-baeren/assets/logos/logo@48px.ico'
  150: '/website-stamm-baeren/assets/logos/logo@150px.png'
  192: '/website-stamm-baeren/assets/logos/logo@192px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Stamm
  url: /stamm/
- title: Abenteuer
  url: /abenteuer/
- title: Kalender
  url: /kalender/
- title: Mitglied werden?
  url: /kontakt/
- title: Suche
  url: /suche/

navigation_footer:
- title: Impressum
  url: /impressum

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Facebook: https://www.facebook.com/Stamm.Baeren
  link: https://www.stamm-baeren.com
  RSS: /website-stamm-baeren/feed.xml
  Email: mailto:stara@stamm-baeren.com

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true
