#theme: alembic-jekyll-theme
remote_theme: daviddarnes/alembic

# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections settings
# 6. Jekyll defaults settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jekyll-remote-theme
- jemoji

# 3. Gem settings
paginate: 4 # jekyll-paginate > items per page
paginate_path: abenteuer/seite:num # jekyll-paginate > blog page
# jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
# twitter:
#  username: DavidDarnes # jekyll-seo-tag > Owners twitter username
author: Stamm Bären # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Stamm Bären Neuried # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.facebook.com/Stamm.Baeren
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Berlin # Timezone for blog posts and alike

# 5. Collections settings
collections:
  posts:
    title: Abenteuer # Needed for Siteleaf
    output: true
    description: "Eine Auswahl vergangener Abenteuer" # The post list page content
    feature_text: Heute hier, morgen dort...
    feature_image: "https://picsum.photos/2560/600?image=866"
    sort_by: date

# 6. Jekyll Default settings (see https://jekyllrb.com/docs/configuration/front-matter-defaults/)
defaults:

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: de-GE # Set the site language
title: "Stamm Bären Neuried" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/favicon.ico" # Site logo, also used in jekyll-seo-tag
description: "Wir sind als örtliche Gruppe in Neuried (Bayern) Mitglied des [BdP e.V.](https://www.pfadfinden.de) und Teil der weltweiten Jugendbewegung Pfadfinden." # Site description and default description, also used in jekyll-seo-tag
url: "https://www.stamm-baeren.de" # Site url, also used in jekyll-seo-tag
baseurl: ""
# repo: "https://github.com/daviddarnes/alembic"
email: "stara-stamm-baeren@googlegroups.com"
service_worker: false # Will turn off the service worker if set to false
css_inline: false # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/favicon-16x16.png'
  32: '/assets/logos/favicon-32x32.png'
  96: '/assets/logos/favicon-96x96.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Stamm
  url: /stamm/
- title: Abenteuer
  url: /abenteuer/
- title: Kalender
  url: /kalender/
- title: Kontakt
  url: /kontakt/
- title: Suche
  url: /suche/

navigation_footer:
- title: Impressum
  url: /impressum

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Facebook: https://www.facebook.com/Stamm.Baeren
  link: https://www.stamm-baeren.de
  RSS: /feed.xml
  Email: mailto:stara-stamm-baeren@googlegroups.com

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true
