name: Build and commit website to gh-pages

on:
  push:
    branches:
      - master

jobs:
  prepare-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.3.1
        env:
          target_branch: gh-pages
          target_path: /
          token: ${{ secrets.GITHUB_TOKEN }}
